version: "3.8"

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: travel_app
    restart: always
    environment:
      POSTGRES_USER: aarishchaudhary
      POSTGRES_PASSWORD: aarisH2005
      POSTGRES_DB: travel_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: