BEGIN;

ALTER TABLE riders ADD COLUMN IF NOT EXISTS password_hash TEXT NOT NULL DEFAULT '';
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS password_hash TEXT NOT NULL DEFAULT '';

ALTER TABLE drivers ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'OFFLINE';

ALTER TABLE drivers
    ADD CONSTRAINT drivers_status_check CHECK (status IN ('ONLINE', 'OFFLINE', 'ON_TRIP'));

COMMIT;